apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minecraft.persistentVolumeClaimName" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
