apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft.fullname" . }}-headless
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
  type: ClusterIP 
  clusterIP: None
  ports:
    - port: {{ .Values.service.minecraftPort }}
      targetPort: minecraft 
      protocol: TCP
      name: minecraft
    {{- if .Values.minecraft.ENABLE_RCON }}
    - port: {{ .Values.service.rconPort }}
      targetPort: rcon
      protocol: TCP 
      name: rcon 
    {{- end }}
    {{- with .Values.service.extraPorts }}
    {{- toYaml . | nindent 4 }} 
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft.fullname" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }} 
  ports:
    - port: {{ .Values.service.minecraftPort }}
      targetPort: minecraft 
      protocol: TCP
      name: minecraft
    {{- if .Values.minecraft.ENABLE_RCON }}
    - port: {{ .Values.service.rconPort }}
      targetPort: rcon
      protocol: TCP 
      name: rcon 
    {{- end }}
    {{- with .Values.service.extraPorts }}
    {{- toYaml . | nindent 4 }} 
    {{- end }}
